-- Story 2.1 foundation migration
-- Purpose: prepare storage tables for competitions ingestion and future course
-- synchronization while preserving snake_case naming and idempotent keys.

create table if not exists app_public.courses (
  id bigint generated by default as identity primary key,
  course_id text not null,
  course_name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint courses_course_id_key unique (course_id)
);

create table if not exists app_public.competitions (
  id bigint generated by default as identity primary key,
  competition_id text not null,
  metrix_id text,
  competition_name text not null,
  competition_date date not null,
  course_name text,
  record_type text,
  players_count integer,
  raw_payload jsonb,
  source_fetched_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint competitions_competition_id_key unique (competition_id),
  constraint competitions_metrix_id_key unique (metrix_id),
  constraint competitions_players_count_check check (
    players_count is null or players_count >= 0
  )
);

create index if not exists competitions_competition_date_idx
  on app_public.competitions (competition_date);
