-- Story 2.6
-- Purpose: persist manually managed tournament categories with editable
-- metadata for segments count and rating boundaries.

create table if not exists app_public.tournament_categories (
  id bigint generated by default as identity primary key,
  category_id text not null,
  name text not null,
  description text not null,
  segments_count integer not null,
  rating_gte double precision not null,
  rating_lt double precision not null,
  coefficient numeric(10, 2) not null default 1.00,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint tournament_categories_category_id_key unique (category_id),
  constraint tournament_categories_name_check check (char_length(btrim(name)) > 0),
  constraint tournament_categories_description_check check (char_length(btrim(description)) > 0),
  constraint tournament_categories_segments_count_check check (segments_count > 0),
  constraint tournament_categories_rating_gte_check check (rating_gte >= 0),
  constraint tournament_categories_rating_lt_check check (rating_lt >= 0),
  constraint tournament_categories_rating_range_check check (rating_lt > rating_gte),
  constraint tournament_categories_coefficient_check check (coefficient >= 0)
);

create index if not exists tournament_categories_name_idx
  on app_public.tournament_categories (name);
