-- Story rating-phase начисление очков
-- Purpose: store per-competition season points per player.

create table if not exists app_public.season_standings (
  id bigint generated by default as identity primary key,
  season_code text not null,
  competition_id text not null,
  player_id text not null,
  category_id text,
  placement integer not null,
  players_count integer not null,
  raw_points numeric(10, 2) not null,
  coefficient numeric(8, 4) not null,
  season_points numeric(10, 2) not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint season_standings_season_competition_player_key
    unique (season_code, competition_id, player_id),
  constraint season_standings_season_code_fkey
    foreign key (season_code) references app_public.seasons (season_code)
    on delete cascade,
  constraint season_standings_competition_id_fkey
    foreign key (competition_id) references app_public.competitions (competition_id)
    on delete cascade,
  constraint season_standings_player_id_fkey
    foreign key (player_id) references app_public.players (player_id)
    on delete cascade,
  constraint season_standings_category_id_fkey
    foreign key (category_id) references app_public.tournament_categories (category_id)
    on delete set null,
  constraint season_standings_placement_check check (placement > 0),
  constraint season_standings_players_count_check check (players_count >= 8),
  constraint season_standings_placement_players_bound_check check (placement <= players_count),
  constraint season_standings_raw_points_check check (raw_points >= 0),
  constraint season_standings_coefficient_check check (coefficient >= 0),
  constraint season_standings_season_points_check check (season_points >= 0)
);

create index if not exists season_standings_season_idx
  on app_public.season_standings (season_code);

create index if not exists season_standings_player_idx
  on app_public.season_standings (player_id);

create index if not exists season_standings_competition_idx
  on app_public.season_standings (competition_id);
